---
# Minimal single-lab configuration.
clab_lab_name: "ne-config-kit-example"
# clab_inventory: "/clab/clab-ne-config-kit-example/ansible-inventory.yml"

target_hosts: "nokia_srlinux"
backup_root: "/nck-backups"
backup_filename: "running.conf"
backup_filename_template: "<clab_lab_name>__<ne_name>__<time-stamp>.conf"

clab_kind_credentials:
  nokia_srlinux:
    username: admin
    password: NokiaSrl1!
