---
# Per-host credential overrides take precedence over kind defaults.
clab_lab_name: "ne-config-kit-example"

target_hosts: "all"
backup_root: "/backups"
backup_filename: "running.conf"

clab_kind_credentials:
  nokia_srlinux:
    username: admin
    password: NokiaSrl1!

clab_host_credentials:
  clab-ne-config-kit-example-srl1:
    username: admin2
    password: Srl1Diff!
