---
- name: Backup running configurations
  hosts: "{{ target_hosts | default('routers') }}"
  gather_facts: false
  tasks:
    - name: Run backup workflow
      ansible.builtin.import_role:
        name: common
        tasks_from: backup
